"""Add number of  tasks completed column

Revision ID: 5e8982aea1ef
Revises: 6b7325da9331
Create Date: 2025-01-04 18:50:49.963825

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e8982aea1ef"
down_revision = "6b7325da9331"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tasks_completed",
                            sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("tasks_completed")

    # ### end Alembic commands ###
