"""Create user and task tables

Revision ID: 868a910249be
Revises: 
Create Date: 2025-01-04 18:44:02.793639

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "868a910249be"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("xp", sa.Float(), nullable=False,
                  server_default=sa.text("0")),
        sa.Column(
            "xp_required", sa.Float(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column("total_xp", sa.Float(), nullable=False,
                  server_default=sa.text("0")),
        sa.Column("level", sa.Integer(), nullable=False,
                  server_default=sa.text("1")),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("original_due_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("repeat_interval", sa.Integer(), nullable=False),
        sa.Column("repeat_often", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("user")
    # ### end Alembic commands ###
