"""Add rating score

Revision ID: ca738f81bbd0
Revises: fc7b30bd8065
Create Date: 2025-02-12 18:20:12.545218

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca738f81bbd0"
down_revision = "fc7b30bd8065"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "streak",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "completed",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=False,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rating", sa.Float(), server_default="0", nullable=False)
        )
        batch_op.alter_column(
            "tasks_completed",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "last_time_clicked",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("'2025-01-20 00:00:00'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "last_time_clicked",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("'2025-01-20 00:00:00'"),
        )
        batch_op.alter_column(
            "tasks_completed",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.drop_column("rating")

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "completed",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "streak",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###
