"""Add time multiplier

Revision ID: fc7b30bd8065
Revises: 28e53a4e60fe
Create Date: 2025-01-20 21:04:17.318407

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc7b30bd8065"
down_revision = "28e53a4e60fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "streak",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "completed",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=False,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_time_clicked",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "time_multiplier", sa.Integer(), server_default="1", nullable=False
            )
        )
        batch_op.alter_column(
            "tasks_completed",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "tasks_completed",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.drop_column("time_multiplier")
        batch_op.drop_column("last_time_clicked")

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "completed",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "streak",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###
